name: hello-action-world
on:
  push:
    branches: ["main"]
jobs:
  #- name: Hello-world-event
  hello-world-job:
     runs-on: ubuntu/latest
     steps:
       - name: checkout repo code
         uses: checkout/version@v4
       - run: echo "$(cat hello-world.txt)"
